/**
# TypeScript Type-Level Programming Memo

A collection of personal notes on TypeScript type-level programming.  
It covers everything from basic tips to traps I often fall into.

Difficulty levels are mixed, and the content will be updated sporadically.  
Code validation and version history can be tracked via commit logs.

# Article
## Note for Equality
**tl;dr**: `IsEqual` is a sophisticated utility, but union/intersection duplicates and overloads may break strict equality.

As I described above, although these codes were checked by CI/CD, we should clarify which equality function is used.
TypeScript doesn't have a built-in type to determine whether type `A` is equal to another type `B` or not.

In this article, I've adopted this definition as an equality function; it's a popular definition of `IsEqual`.
*/
export type IsEqual<A, B> =
  (<G>() => G extends (A & G) | G ? 1 : 2) extends <G>() => G extends (B & G) | G ? 1 : 2
    ? true
    : false;
/**
But this definition isn't perfect.
This fails to detect equality in identical union/intersection cases, e.g., `A | A` or `A & A`, because TypeScript doesn't simplify them automatically.
(I pushed some fix PRs to [type-fest](https://github.com/sindresorhus/type-fest/commits/main/source/is-equal.d.ts), including regression fixes.)

And, assuming that `A` and `B` extend `object`, and their keys are not identical to the other's, a mapped type over `keyof (A & B)` and the corresponding values are not considered equal to `A & B`.
In other words, `{[K in keyof (A & B)]: (A & B)[K]}` is not equal to `A & B` in this condition.

And, duplicated overload definitions, e.g., `{(arg: string): number, (arg: string): number}`, are not automatically simplified to `{(arg: string): number}` and they are not considered equal.

And, this is a more critical case, I think, `unknown` and `never` arguments break this equality as we see below.
*/
// @ts-expect-error:
const Test_IsEqual_Unknown_Never: false = {} as IsEqual<unknown, never>;
// @ts-expect-error:
const Test_IsEqual_Never_Unknown: false = {} as IsEqual<never, unknown>;
const Test_IsEqual_Unknown_Never_Tuple: false = {} as IsEqual<[unknown], [never]>;
const Test_IsEqual_Never_Unknown_Tuple: false = {} as IsEqual<[never], [unknown]>;
/**
**Note** - See also this TypeScript PR: [Merge trivially mergeable intersection types for identity comparison]( https://github.com/microsoft/TypeScript/pull/60726 )
*/
/**
## Unions or Intersections are not ordered
**tl;dr**: TypeScript unions do not guarantee order; `0 | 1` vs `1 | 0` are identical at type level.

This is widely misunderstood, as seen in several issues, so I wrote it down just in case.

- `0 | 1` generated by `[0, 1][number]`
- `0 | 1` generated by appending `1` to `0` via union
- `'a' | 'b'` generated by `keyof {a: 0, b: 1}`

TypeScript doesn't ensure these unions are ordered e.g. `0 | 1`.
See [this issue comment.]( https://github.com/microsoft/TypeScript/issues/13298#issuecomment-468375328 )
*/
/**
## Extends and equality
**tl;dr**: `extends` checks assignability, not strict equality; use `[A,B] extends [B,A]` or `IsEqual`.

This section considers cases where `extends` is used as a simplified equality check.  
For example, suppose we define a function, e.g. `IsString<T>`, that returns only `true` or `false` (i.e., not the `boolean` type). The question is where and how to perform the equality check.

The simplest approach is usually to write `IsString<T> extends true`. However, if we instead write `true extends IsString<T>`, and `T` is unintentionally distributed due to union distribution, the right-hand side may become `true | false` (i.e., `boolean`), causing the check to pass unintentionally.  
This can occur not only within type-level functions due to distribution, but also when a union type is unintentionally passed as a type argument.

Conversely, if the function may return `never`, the correct ordering becomes `true extends IsString<T>`. However, this does not account for cases where `boolean` or even `unknown` may be returned incorrectly.

In the end, a safer approach is to use `[A, B] extends [B, A]`, or to explicitly use an equality utility such as `IsEqual<T, U> extends true`.
*/
type _Concat<A extends boolean, B extends boolean> = `${A}/${B}`;
type Test0<A extends boolean, B extends boolean> = [A, B] extends [infer a, infer b]
  ? // @ts-expect-error:
    `${_Concat<a, b>}`
  : never;
// @ts-expect-error:
type Test1<P> = P extends [infer a, infer b] ? `${_Concat<a, b>}` : never;
type Test2<P> = P extends infer pp extends [boolean, boolean] ? _Concat<pp[0], pp[1]> : never;
const _test0: IsEqual<Test0<true, false>, "true/false"> = true;
const _test1: IsEqual<Test1<[true, false]>, "true/false"> = true;
const _test2: IsEqual<Test2<[true, false]>, "true/false"> = true;
/**
`{a: A, b: B}` and `{a: A} & {b: B}`  are not considered equal by `IsEqual` as mentioned earlier.
But, this inconsistency is not limited to equality checks and can unintentionally affect utilities such as `UnionToTuple`.
*/
type A = Exclude<{readonly a: 0} | {a: 0}, {a: 0}>; //=> never
const ExpectRO_0: false = {} as IsEqual<A, {readonly a: 0}>
type UnionToIntersection<U> = (U extends unknown ? (distributedUnion: U) => void : never) extends ((mergedIntersection: infer Intersection) => void)
  ? Intersection & U
  : never;
export type UnionMember<T> =
  [T] extends [never]
    ? never
    : UnionToIntersection<T extends any ? () => T : never> extends () => (infer R)
			? R
			: never;
type UnionToTuple<T, L = UnionMember<T>> =
  [T] extends [never]
    ? [...UnionToTuple<Exclude<T, L>>, L]
    : [];
type ExpectedTuple = UnionToTuple<{readonly a: 0} | {a: 0}>
const ExpectedTuple_0: true = {} as IsEqual<[], ExpectedTuple>
/**
## never or any type in Template Literal
**tl;dr**: `never` collapses the whole template to `never`; `any` preserves the string.

Both return `never`, ignoring the rest of the string.
*/
const ExpectNever_0: true = {} as IsEqual<never, `${never}`>;
const ExpectNever_1: true = {} as IsEqual<never, `${never}something`>;
/**
I added those two cases just in case.
*/
const ExpectString_0: true = {} as IsEqual<"null", `${null}`>;
const ExpectString_1: true = {} as IsEqual<"undefined", `${undefined}`>;
/**
Against `never`, template literals including `any` return themselves.
*/
const ExpectAny_0: false = {} as IsEqual<any, `${any}/something`>;
const ExpectAny_1: false = {} as IsEqual<any, `${any}`>;
const ExpectAny_2: false = {} as IsEqual<`any`, `${any}/something`>;
const ExpectAny_3: false = {} as IsEqual<`any`, `${any}`>;
const ExpectAny_4: true = {} as IsEqual<`${any}/something`, `${any}/something`>;
const ExpectAny_5: true = {} as IsEqual<`${any}`, `${any}`>;
/**
## Xor idiom
**tl;dr**: `F<A> xor G<B>` if neither `F<A>` nor `G<B>` returns `never`.
*/
type F<T> = T extends string ? true : false;
type G<T> = T extends number ? true : false;
type XorTest0<A, B> = F<A> & G<B> extends never ? true : false;
const XorTest_ExpectedPass_True_True: true = {} as IsEqual<false, XorTest0<"a", 1>>;
const XorTest_ExpectedPass_False_False: true = {} as IsEqual<false, XorTest0<false, true>>;
const XorTest_ExpectedPass_True_False: true = {} as IsEqual<true, XorTest0<"a", true>>;
const XorTest_ExpectedPass_False_True: true = {} as IsEqual<true, XorTest0<false, 1>>;
/**
## Arguments forced to be tuple
**tl;dr**: Literal tuples, `as const`, and constant variables behave differently; ForceTuple can enforce expected shape.

There are three kinds of tuples that can be passed to a function (when classified by type).

- Passed directly as a tuple literal
- Passed as a tuple literal with as const
- Passed via a variable that was defined with as const

The tricky part is that the latter two are not strictly the same.

If you try to distinguish them using only readonly, the variable-based case cannot be properly detected. On the other hand, if you use `[X, Y, Z]`, it can of course accept tuples, but in the first case, `[0, 1, 2]` gets widened to `[number, number, number]`, so it cannot be treated as a singleton tuple.
*/
const f0 = <A extends unknown[]>(a: A): A => a;
const _testf0a = f0([0, 1, 2]);
const _testf0b = f0([0, 1, 2] as const);
const fa0 = [0, 1, 2] as const;
// @ts-expect-error:
const _testf0c = f0(fa0);
const f1 = <A extends [unknown, unknown, unknown]>(a: A) => a;
const _testf1a = f1([0, 1, 2]);
const _testf1b = f1([0, 1, 2] as const);
const fa1 = [0, 1, 2] as const;
// @ts-expect-error:
const _testf1c = f1(fa1);
/**
Therefore, the argument type is first captured as a generic, and then checked via a type-level function for `readonly`. If it does not satisfy the condition, the argument type is replaced with never. See the type constraint.

Note that without going through a type-level function, it is not possible to expand this kind of logic inline. (Needs further verification.)
*/
type ForceTuple<S> = S extends readonly [infer a, infer b, infer c] | [infer a, infer b, infer c]
  ? [a, b, c] extends S
    ? S
    : never
  : never;
/**
The full version is [here]( https://github.com/taiyakihitotsu/foxp/blob/431b2b28ef4e0e087da2fcd8b5b33d9e75f33595/src/type-util.ts#L90 ). (However, this currently only supports up to 8 elements, so further improvement is needed.)
*/
const f2 = <A>(a: A extends (ForceTuple<A> extends never ? never : A) ? A : never) => a;
// @ts-expect-error:
const _testf2a = f2([0, 1, 2]);
const f2aa = [0, 1, 2];
// @ts-expect-error:
const _testf2aa = f2(f2aa);
const _testf2b = f2([0, 1, 2] as const);
const fa2 = [0, 1, 2] as const;
const _testf2c = f2(fa2);
/**
## Currying of Generic Types
**tl;dr**: Currying generic types increases type safety without defaults, useful for type-level programming.

Generic type arguments can be separated by defining a higher-order function.

Useful when we want to make an argument stricter by `extends` but we don't want to add a default type.
This pattern occurs frequently.
*/
const defc =
  <X extends number, Y extends boolean>() =>
  <Z extends string>(_x: X, _y: Y, _z: Z): { _x: X; _y: Y; _z: Z } => ({
    _x: 1 as X,
    _y: true as Y,
    _z: _z,
  });
const testdefc_0 = defc()(1, true, "z");
const testdefc_1_fn = defc<0, false>();
// @ts-expect-error:
const testdefc_1 = testdefc_1_fn(1, true, "z");
const testdefc_2_fn = defc<1, true>();
const testdefc_2 = testdefc_2_fn(1, true, "z");
const testdefc_3_fn = defc<1, true>();
// @ts-expect-error:
const testdefc_3 = testdefc_2_fn<"x">(1, true, "z");
/**
## Extract type from overload.
**tl;dr**: Slurp overloads requires `(...args_: infer A0): infer R0;`.

- overloads in object can be extracted via `Pick<T, keyof T>`
- overloads in object can NOT be extracted via `Omit<T, Keyof T>`

In other words, `Pick<T, Keyof T>` and `Omit<T, Keyof T>` return the same result if object composed only of overloads is passed. Both return `{}`.

If we want to pick overloads, we can define, define `(...args_: infer A0): infer R0;` as a number you want to pick. I think there's no syntax to pick them without restriction.

These pairs of `An` and `Rn` stored in this way, aren't simplified by intersection `&` automatically.
So we should combine them into union `|` first, then dedupe it, then use [UnionToIntersection]( https://github.com/sindresorhus/type-fest/blob/main/source/union-to-intersection.d.ts ) finally.
*/
type Overload = { (a: number): string; (a: string): number };
type OverloadSup = { (a: number): string };
const _Test_EqOverload_0: false = {} as IsEqual<Overload, OverloadSup>;
const _Test_EqOverload_1: false = {} as [Overload, OverloadSup] extends [OverloadSup, Overload]
  ? true
  : false;
/**
## Scope of keyof
**tl;dr**: `keyof` ignores overloads and `readonly`/optional modifiers.

First, `keyof` ignores overloads as we see above.
So `Pick<T, keyof T>` returns `T` excluded for all of overloads.

Second, `keyof` omits information about `readonly` and/or optional.
Use `{[K in keyof T]: T[K]}` syntax if you want to keep them.
*/
type WithOverload = { (...args_: any[]): number; key0: "value0"; key1: 1 };
const _Test_Keyof_0: true = {} as IsEqual<"key0" | "key1", keyof WithOverload>;

/**
## Pitfall of Exclude
**tl;dr**: `Exclude` uses assignability, not equality; beware with `readonly` or subset keys.

`Exclude` uses assignability not equality to detect whether the 1st type should be removed by the 2nd or not.
This specification is clearly stated in [this official document]( https://www.typescriptlang.org/docs/handbook/utility-types.html#excludeuniontype-excludedmembers )

> Constructs a type by excluding from UnionType all union members that are **assignable** to ExcludedMembers.

That's why these 2 cases return `never`.

- `Exclude<{a: 0}, {readonly a: 0}>`
- `Exclude<{a: 0, b: 0}, {a: 0}>`

`Exclude`'s role is often explained as "remove a type", but it's lack of context. This is correct when based on assignability, but not when based on equality.
*/
type TestExcludeRO = Exclude<{ a: 0 }, { readonly a: 0 }>;
const _TestExcludeRO: true = {} as IsEqual<never, TestExcludeRO>;
type TestExcludeSub = Exclude<{ a: 0; b: 0 }, { a: 0 }>;
const _TestExcludeSub: true = {} as IsEqual<never, TestExcludeSub>;
type TestExcludeSup = Exclude<{ a: 0 }, { a: 0; b: 0 }>;
const _TestExcludeSup: true = {} as IsEqual<{ a: 0 }, TestExcludeSup>;
/**
## Equality via `extends`
**tl;dr**: `[A,B] extends [B,A]` detects equality better than `extends`, but `readonly` are tricky.

`extends` doesn't mean that `A` and `B` are equal, although it is sometimes used as part of an equality check.
I found an internal memorandum mentioning this.

We can use a more structured syntax, `[A, B] extends [B, A] ? ...`, but this is also wrong definition if you want to seek a strict equality.
This depends on assignability, not equality, so `readonly` is **ignored**.

We should state the edge-case about identical union/intersection case.
This **crossed** equality syntax properly detect that `A | A` and `A` are equal.
*/
type ExtendsRO_0 = { a: 0 } extends { readonly a: 0 } ? true : false;
type ExtendsRO_1 = { readonly a: 0 } extends { a: 0 } ? true : false;
const _Test_ExtendsRO_0: true = {} as IsEqual<true, ExtendsRO_0>;
const _Test_ExtendsRO_1: true = {} as IsEqual<true, ExtendsRO_1>;
type ExtendsROTuple_0 = [0, 1, 2] extends readonly [0, 1, 2] ? true : false;
type ExtendsROTuple_1 = readonly [0, 1, 2] extends [0, 1, 2] ? true : false;
const _Test_ExtendsROTuple_0: true = {} as IsEqual<true, ExtendsROTuple_0>;
const _Test_ExtendsROTuple_1: true = {} as IsEqual<false, ExtendsROTuple_1>;
/**
## Loss of Assignability in Conditional Types
**tl;dr**: Generic conditional types may lose assignability; wrapping in tuples often preserves it.

Assignability would be lost in a generic type using conditional type.
This is related to delayed evaluation of types though, we will skip the theory for now.
I intended to provide this information briefly, as a memo, so I listed some patterns.
*/
/**
Kept assignability.
*/
type Validate<T> = T extends any ? true : false;
type Assignability<T, V extends Validate<T>> = any;
type TestAssignability<T> = Assignability<T, true>;
/**
Kept assignability.
See the latter 2 case which have unreachable `else` branch.
*/
type Validate_Self_Tuple<T> = [T] extends [T] ? true : false;
type Assignability_Self_Tuple<T, V extends Validate_Self_Tuple<T>> = any;
type TestAssignability_Self_Tuple<T> = Assignability_Self_Tuple<T, true>;
/**
Lost assignability in `T extends T` syntax.
`else` is unreachable but this isn't evaluated to be `true` directly.
*/
type Validate_Self<T> = T extends T ? true : false;
type Assignability_Self<T, V extends Validate_Self<T>> = any;
// @ts-expect-error: "Type 'boolean' does not satisfy the constraint 'Validate_Self<T>'. [2344]"
type TestAssignability_Self<T> = Assignability_Self<T, true>;
/**
Lost assignability in `extends infer` syntax.
`else` is unreachable but this isn't evaluated to be `true` directly.
*/
type Validate_Infer<T> = T extends infer A ? true : false;
type Assignability_Infer<T, V extends Validate_Infer<T>> = any;
// @ts-expect-error: "Type 'boolean' does not satisfy the constraint 'Validate_Infer<T>'. [2344]"
type TestAssignability_Infer<T> = Assignability_Infer<T, true>;
/**
If wrapping with tuple, the above `infer` case cannot **fix**.
*/
type Validate_Infer_Tuple<T> = [T] extends [infer A] ? true : false;
type Assignability_Infer_Tuple<T, V extends Validate_Infer_Tuple<T>> = any;
// @ts-expect-error: "Type 'boolean' does not satisfy the constraint 'Validate_Infer_Tuple<T>'. [2344]"
type TestAssignability_Infer_Tuple<T> = Assignability_Infer_Tuple<T, true>;
/**
Lost assignability, the entire left side is wrapped in a tuple.
`extends any` syntax must be reached so it must return `[true]` yet.
*/
type Validate_Unknown_Tuple_Clause<T> = [T extends any ? true : false] extends [true]
  ? true
  : false;
type Assignability_Unknown_Tuple_Clause<T, V extends Validate_Unknown_Tuple_Clause<T>> = any;
// @ts-expect-error: "Type 'boolean' does not satisfy the constraint 'Validate_Unknown_Tuple_Clause<T>'. [2344]"
type TestAssignability_Unknown_Tuple_Clause<T> = Assignability_Unknown_Tuple_Clause<T, true>;
/**
## Type Extraction from Template Literal
**tl;dr**: Use `infer` with constraints carefully; `number/${number}` ≠ literal `number`s; `never` collapses inference.

```typescript
`number/${number}`
```

It is possible for template literals to include types.
Here is one way to extract them.
*/
type LiteralType = `number/${number}`;
type PickType<T> = T extends `number/${infer s extends number}` ? s : 0;
const _Test_LiteralPickType_0: true = {} as IsEqual<number, PickType<LiteralType>>;
/**
Note this pitfall:

```typescript
extends `${infer A extends number}`
```

This syntax is valid, but it does not ensure that `A` must be a literal number like `0`, `1` or so, because `A` would be `number`.
(This applies for `boolean`, etc.)
So we should be careful with this.

Additionally, template literals including `never` are inferred to be `never` as described above, be careful if `F<T>` can return `never`.
```typescript
${F<T>} extends
```
*/
type PickTypeStrict<T> = T extends `number/${infer s extends number}` ? [number] extends [s] ? 'number' : s : 'not-number'
const _Test_LiteralPickTypeStrict_0: true = {} as IsEqual<'number', PickTypeStrict<`number/${number}`>>
const _Test_LiteralPickTypeStrict_1: true = {} as IsEqual<0, PickTypeStrict<`number/${0}`>>
const _Test_LiteralPickTypeStrict_2: true = {} as IsEqual<'not-number', PickTypeStrict<`number/${string}`>>
/**
```typescript
`number/${'0'}`
```

Check this case, `'0'` is inferred as the same as `0`.
*/
const _Test_LiteralPickTypeStrict_3: true = {} as IsEqual<0, PickTypeStrict<`number/${'0'}`>>
/**
## Validation for Arguments
**tl;dr**: Use conditional type checks to reject invalid literals at compile time.

Use a generics type that returns a `boolean`, e.g. `GreaterThan<N>` exported by `type-fest` for compile-type validation of function arguments.
This syntax expands conditional types twice.

- Inner: Translate a result `true` to `T`
- Outer: Declare `T` is a type of argument, then test `T` by itself.

It returns `never` if the inner doesn't return `true`, meaning that `T extends never` must fail. Type error occurs finally.
*/
type IsOne<N extends number> = IsEqual<N, 1> extends true ? true : false;
const oneValidateFn = <T>(
  _: T extends (IsOne<T extends number ? T : never> extends true ? 1 : never) ? T : never,
) => 1;
// @ts-expect-error:
oneValidateFn(0);
oneValidateFn(1);
